spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: never
    test:
#      hikari:
#        schema: schema-demo_h2.sql
#      platform: test_h2
      schema: schema-demo_h2.sql
      url: jdbc:h2:file:./temp/data/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      jdbc-url: jdbc:h2:file:./temp/data/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      driverClassName: org.h2.Driver
      username: sa
      password: 123456
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
    test2:
      jdbc-url: jdbc:h2:file:./temp/data/test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      driverClassName: org.h2.Driver
      username: sa
      password: 123456
      minimum-idle: 10
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        web-admin-password: 123456
