spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    platform: test
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://192.168.1.110:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true
#    jdbc-url: jdbc:mysql://192.168.1.110:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true
    url: jdbc:mysql://192.168.56.101:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useServerPrepStmts=true&useAffectedRows=true
    jdbc-url: jdbc:mysql://192.168.56.101:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useServerPrepStmts=true&useAffectedRows=true
    username: root
    password: 123456
    minimum-idle: 10
    maximum-pool-size: 200
    idle-timeout: 300000
    max-lifetime: 1200000
