drop table if exists user CASCADE;
create table user
(
    id          bigint generated by default as identity,
    account     varchar(100) default ''      not null,
    count       int          default '0'     not null,
    create_time bigint       default '0'     not null,
    create_user bigint       default '0'     not null,
    email       varchar(200) default ''      not null,
    enabled     boolean      default 'true'  not null,
    locked      boolean      default 'false' not null,
    name        varchar(100) default ''      not null,
    update_time bigint       default '0'     not null,
    update_user bigint       default '0'     not null,
    primary key (id)
);
