DROP TABLE IF EXISTS `TEST_USER`;
CREATE TABLE `TEST_USER` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
    `CREATE_TIME` bigint(20) DEFAULT '0',
    PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
