drop table if exists TEST_USER CASCADE;
create table TEST_USER
(
    ID   bigint generated by default as identity,
    NAME varchar(100) default '' not null,
    CREATE_TIME bigint       default '0'     not null,
    primary key (ID)
);
